## This app only
## You should be using a deploy key here hence no user or password property
[git]
repo = ""
dir_to_clone = "~/"

[compose]
file = "docker-compose.yaml"
force_repull = true

[registry]
private=false
url=""
username=""
password=""

